name = "siren-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


[[kv_namespaces]]
binding = "SIREN"
id = "6206145857a0493a9a4e4672b0be544b" 

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/xiyosenstore/hompage/refs/heads/main/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/xiyosenstore/hompage/refs/heads/main/subs%20(1).html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/xiyosenstore/hompage/refs/heads/main/link.html"
