name = "siren-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  
  { pattern = "collection.linefriends.com.siren-web.benxx.workers.dev", custom_domain = true },  
  { pattern = "ava.game.naver.com.changli.siren-web.benxx.workers.dev", custom_domain = true },
  
  
]
# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



[[kv_namespaces]]
binding = "SIREN"
id = "0f1645175a8e44c5ac7bceea1af5ed78" 

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "2bcfbfba-b446-4ad5-93ad-72af9e008f61"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/xiyosenstore/sirenlink/refs/heads/main/link.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/xiyosenstore/hompage/refs/heads/main/subs%20(1).html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/xiyosenstore/hompage/refs/heads/main/link.html"
